### PR TITLE
Add ability to compare approximate dates with regular ones

### PR DESCRIPTION
**Pull request by bmispelon**
We needed that feature for djangogirls.org so I thought I'd try to contribute it.

I added a few tests and they pass on my local machine (python 2.7 and 3.4).

### CODE REVIEW

**Comment by dracos** [comment]
Oh, thanks! Sorry, have been a bit busy recently, but will hopefully take a look soon.

**Comment by bmispelon** [comment]
Let me know if there's something I can do to help move this forward.

**Comment by dracos** [comment]
I hope to look at this during the Django sprint at DjangoCon EU this week; if you're there, would be good to meet up :)

**Comment by dracos** [comment]
Thanks very much for this! Now merged :) Tweaked stuff to pass flake8, and to fix a `date` reference.

I wonder if you should be able to compare `ApproximateDate(past=True)` as being earlier than any `datetime` date, and same for `future`.

**Pull request closed without merging**
